name: NPM Publish

on:
    release:
        types: [created]
jobs:
    npm:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2

            - uses: actions/setup-node@v1
              with:
                  node-version: '12.x'
                  registry-url: 'https://registry.npmjs.org'

            - name: Install npm dependencies
              run: npm ci

            - name: Test and build package
              run: npm run build

            - name: Publish tag to npm
              if: contains(github.ref, 'tags')
              run: npm publish --access=public
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}